{% set version = "1.5-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-maxlik
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/maxLik_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/maxLik/maxLik_{{ version }}.tar.gz
  sha256: 7cee05be0624b6a76911fa7b0d66f3e1b78460e0c55ed8bc904ce1e8af7bb15d

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-generics
    - r-misctools >=0.6_8
    - r-sandwich
  run:
    - r-base
    - r-generics
    - r-misctools >=0.6_8
    - r-sandwich

test:
  commands:
    - $R -e "library('maxLik')"           # [not win]
    - "\"%R%\" -e \"library('maxLik')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=maxLik
  license: GPL-2.0-or-later
  summary: Functions for Maximum Likelihood (ML) estimation and non-linear optimization, and related tools.  It includes a unified way to call different optimizers, and classes and methods to handle the results from the ML viewpoint.  It also includes a number of convenience tools for testing and developing your own models.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: maxLik
# Version: 1.3-6
# Date: 2019-05-18
# Title: Maximum Likelihood Estimation and Related Tools
# Author: Ott Toomet <otoomet@gmail.com>, Arne Henningsen <arne.henningsen@gmail.com>, with contributions from Spencer Graves and Yves Croissant
# Maintainer: Ott Toomet <otoomet@gmail.com>
# Depends: R (>= 2.4.0), miscTools (>= 0.6-8), methods
# Imports: sandwich
# Suggests: testthat
# Description: Functions for Maximum Likelihood (ML) estimation and non-linear optimization, and related tools.  It includes a unified way to call different optimizers, and classes and methods to handle the results from the ML viewpoint.  It also includes a number of convenience tools for testing and developing your own models.
# License: GPL (>= 2)
# ByteCompile: yes
# NeedsCompilation: no
# Packaged: 2019-05-19 05:40:23 UTC; siim
# Repository: CRAN
# Date/Publication: 2019-05-19 15:45:49 UTC
