appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: b3F7J97YVh3kIoV6lbGNw4/7Q4h2N1SYP+OTg8L/yxci3Y/CZv4mVWg9CTHRkSQzdEMR/oXSXhbiOEFExWMxq1u6WJHlgcU3ubNQtB7B/bMLluwFxZjowGkAP0UekUAoAkKoPd8esAWtN9nA8y6zHBxWb+LcsE6OLREn14sN3MgUZzKIUW0dVCxyqNZr1X8uRMeEqgw1NzQ8gsoUgCiLWsGcgU6X2YWp7+3pf69knjj2aThLX97J88NHim2aQeQIdNQoFmn7q4B+jNeoOa8qlEk0be1YAegG+Fwhclijf04vEPAqD4PAHRZ0uRY5ddFBNdPfRsjI6z5zJF9TguELh5uWfYcYtDtnOrOx22KX5EwmkNohnR6E+K/JJJ5yy99O313INdZHk6XHATdjV6Dtz+8cVEWAiFvm0tnnR89fQlZDja29dudKIKz9VI+sMUe+xFdB+MQLQazxtQfPgaEIPYhNYghjhbrNXDCLWjXK4rPQu/Xj/F6Klqsu5xjr2EZX2rEu+o3d+MY6h35dVigquh6tTkXZ3DNkRUFfp/eLigKOWxcajORr1cloXbz0EjUEmI/a2ignsGa8OP4wvit5hhrzjsS5W+1oWm3Ukm17EQOAjNk7ZlACyj6bpt7RtjLATd0bNL3Daq3CRBDohG46aFW+5+oATV9s6lBPq4wlibk=}
