travis:
  secure:
    BINSTAR_TOKEN: pw6JSPCpEm66u6QGCXzPPyORC0Wesilp1Uk72d02OBG+4mjpbLbtVlfTgiPE6ahvUfV4j5ii1FJcvAjTLdzKKamAxpJ2UfRMUYr+wLojy/m0WpL6t9ngzJe9O6zdJnZSNZqpl6WsYljwSRNoQPncc7BViYdOQSYH9oi0ay6nORlLWNL3woQtOdO7dHyMPEwBeJBKguMtRmtRk7Ih4bC8g64V74izu7BfCjglEYocGDS2Bl6tV7/mC8qhvFsCaB+qU0AJ4bwC9ow325YRx8+A0K/9O8ye37n9oZOOtdFIQvZ8K5g1vr+KNxepagjLKCAaWwtf6w3AK3VQt1+33mmjuJWWoW9pRG44BArtWTlEJN97C24cCaSMD2iqMKrkxCKBX6chfX0U9Li2PppZmrUU81hv8Xuq6Uyr4yQRshS9OvIqK4qJyn+9CkFFJ7ZLpNFch7b2kZK7VuT9960DodBf+Cs6DUqZdMJBOUVr0npEORW1sBGvYT7AiGtalm/QkPlV5TFEXQzBbfZPns6Yy+dNIp4nsf1omgsTOE1CrTlzHI9CNwZsvhcyZz4UnGvZ7m+id0Yo/shsanW+PbCNstAJVseVBHPTyf7u4bZxvI328aRNvvEV8UvCYgdbgSCd15I4bAqkQFKXyKaFVNsfGvfdSqyFqKsShDNc/aavOEhXCdQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
